version: '3'

services:
  backend-whatsapp:
    image: hannanhunny/backend-whatsapp:1.0
    ports:
      - "4000:4000"
    env_file:
      - ./.env.test
    networks:
      - mybridge

  deployback:
    image: deployback:1.0
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      - mybridge

networks:
  mybridge:
    driver: bridge
